app:
  name: MyApp
  version: 1.0.0
  debug: true

services:
  spotify:
    client_id: ${SPOTIFY_CLIENT_ID}
    client_secret: ${SPOTIFY_CLIENT_SECRET}

  lastfm:
    api_key: ${LASTFM_API_KEY}
    api_secret: ${LASTFM_API_SECRET}

  tikapi:
    key: ${TIKAPI_KEY}

  google:
    bucket_name: ${GOOGLE_BUCKET_NAME}
    google_json: ${GOOGLE_APPLICATION_CREDENTIALS}

  openai:
    api_key: ${OPENAI_KEY}
